name: Jest Code Coverage Report

on:
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs:
  compare-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: vgrafe/jest-reports@v0.1.5