name: Jest Code Coverage Report

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  jest_coverage:
    name: Jest Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install # or yarn install

    - name: Run Jest tests with coverage
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        # Optionally, you can provide custom test command if needed
        test-command: "yarn test"
        # You can run tests related to changes only
        # changes-only: true
        # Or specify a working directory
        # working-directory: "frontend"
        # You may want to silence code coverage comment if not needed
        # coverage-comment: false