name: Jest Code Coverage Report

on:
  pull_request:
    branches:
      - '*'

jobs:
  jest_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Jest Code Coverage
        uses: ziishaned/jest-reporter-action@v0.1.1
        with:
          github-token: ${{ secrets.TOKEN }}
          test-command: "yarn jest --coverage"
