name: Jest Code Coverage Report

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn install

      - name: Hello world action step
        id: hello
        uses: raulanatol/jest-coverage-comment-action@main
        with:
          github-token: ${{ secrets.TOKEN }}
          jest-command: 'npx jest --collectCoverageFrom="src/**/*.{js,jsx,ts,tsx}" --coverage --collectCoverage=true --coverageDirectory="./" --coverageReporters="json-summary" --forceExit --detectOpenHandles'